from lista import Lista
lista = Lista()
lista.imprimir()
lista.adicionar( 5 )
lista.imprimir()
lista.adicionar( 2 )
lista.imprimir()
lista.adicionar( 76 )
lista.imprimir()
lista.adicionar( 79 )
lista.imprimir()
lista.adicionarNoinicio(20)
lista.imprimir()
lista.excluir(2)
lista.adicionarNoinicio(50)
lista.imprimir()
lista.excluir(76)
lista.alterar(79, 47)
lista.imprimirInverso()